# Generated by Django 5.1.4 on 2025-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_username'),
    ]

    operations = [
    ]
