# Generated by Django 5.1.4 on 2025-03-12 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20250303_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=60, verbose_name='País')),
                ('ciudad', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
