# Generated by Django 5.1.4 on 2025-03-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
