# Generated by Django 5.1.4 on 2025-05-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion', to='ubicacion.city'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=4.1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=4.1, max_digits=9),
            preserve_default=False,
        ),
    ]
