# Generated by Django 5.1.4 on 2025-03-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='municipio_id',
            new_name='municipio',
        ),
    ]
