# Generated by Django 5.1.4 on 2025-03-03 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articuloetiqueta',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='articulos.articulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='articulos.categoria'),
        ),
        migrations.AddField(
            model_name='articuloetiqueta',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulos.etiqueta'),
        ),
    ]
