# Generated by Django 5.1.4 on 2025-03-02 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_publiacion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Vendido'), ('3', 'En proceso')], default='1', max_length=1, verbose_name='Estado del articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ubicacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='ubicacion.ubicacion'),
        ),
        migrations.CreateModel(
            name='ArticuloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='articulos.articulo')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulos.etiqueta')),
            ],
            options={
                'verbose_name': 'Articulo Etiqueta',
                'verbose_name_plural': 'Articulos Etiquetas',
            },
        ),
    ]
