# Generated by Django 5.1.4 on 2025-05-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_confirmed', models.BooleanField(default=False, verbose_name='Vendedor confirmó')),
                ('buyer_confirmed', models.BooleanField(default=False, verbose_name='Comprador confirmó')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='chat.room')),
            ],
            options={
                'verbose_name': 'Intercambio',
                'verbose_name_plural': 'Intercambios',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Calificación (1-5)')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Comentario')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketflow.exchange')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
