# Generated by Django 5.1.4 on 2025-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(null=True, upload_to='attachmentsChat/')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-send_date'],
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo de Mensaje',
                'verbose_name_plural': 'Tipos de Mensaje',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'Disponible'), ('2', 'Vendido'), ('3', 'En Proceso'), ('4', 'Cancelado')], default='1', max_length=1, verbose_name='Estado del producto')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('chat_type', models.CharField(choices=[('1', 'Grupal'), ('2', 'Privado')], default='2', max_length=1, verbose_name='Tipo de chat')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
            },
        ),
    ]
