# Generated by Django 5.1.4 on 2025-05-16 07:09

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=300, upload_to=apps.products.models.get_image_upload_path)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Oferta')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(null=True, verbose_name='Fecha Fin de la promoción')),
                ('active', models.BooleanField(default=True, verbose_name='Oferta Activa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WishList',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('state', models.CharField(choices=[('1', 'Disponible'), ('2', 'Vendido'), ('3', 'En Proceso'), ('4', 'Cancelado')], default='1', max_length=1, verbose_name='Estado del producto')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('condition', models.CharField(choices=[('1', 'Sin Usar'), ('2', 'En buen Estado(Pocos Usos)'), ('3', 'Uso Moderado'), ('4', 'Desgastado'), ('5', 'Revendido (Tercera Mano)')], default='2', max_length=1, verbose_name='Condicion del producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo', to='ubicacion.ubicacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
