# Generated by Django 5.1.4 on 2025-05-17 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
    ]
